### ISSUE TITLE
Add possibility to set the npc in private mode

### ISSUE THREAD

**Issue by Zarkness2** [TabooLib/adyeshach#6]
My suggestion is to add the possibility to put the npcs in private and that they need certain permission to be displayed for example the skyblock npc to be displayed needs you to have the adyeshach.npc.skyblock permission.

and a few questions the plugin has api? and do you plan to upload the plugin to spigot? and is there any discord group or some site apart from github where to ask for support and that is something faster?

**Comment by Bkm016** [comment]
你好 Zarkness,

Adyeshach 拥有完整的API，可以通过 `AdyeshachEntityVisibleEvent` 事件来实现你的需求。

```kotlin
    @EventHandler
    fun e(e: AdyeshachEntityVisibleEvent) {
        if (e.visible && e.entity.id == "skyblock_npc" && !e.viewer.hasPermission("adyeshach.npc.skyblock")) {
            e.isCancelled = true
        }
    }
```

目前并不打算发布到 Spigot，因为这个插件是知识付费的。以及我们面向的用户多在中国地区，不提供 Discord 服务。

---

Hi Zarkness,

Adyeshach has complete API, you can achieve your needs through the `AdyeshachEntityVisibleEvent` event.

```kotlin
    @EventHandler
    fun e(e: AdyeshachEntityVisibleEvent) {
        if (e.visible && e.entity.id == "skyblock_npc" && !e.viewer.hasPermission("adyeshach.npc.skyblock")) {
            e.isCancelled = true
        }
    }
```

It is not currently planned to be uploaded to spigot, because this plugin is paid for knowledge. And most of our users are in China, don't provide discord service.

You can ask questions in issue page, or email me.

TABOO PROJECT
